### ISSUE TITLE
1.20.2 version pyramid dungeon trap is broken

### ISSUE THREAD

**Issue by thisisyoursus** [XxRexRaptorxX/Additional-Structures#11]
![2024-08-30_20 17 03](https://github.com/user-attachments/assets/8a7a456c-a975-46ac-bd26-90a69d9304e0)
![2024-08-30_20 17 10](https://github.com/user-attachments/assets/16e04d38-6e2f-4392-a345-e5ab72fdee29)

**Comment by thisisyoursus** [comment]
i using forge Rex's-AdditionalStructures-1.20.x-(v.4.2.1)

**Comment by XxRexRaptorxX** [comment]
Thanks for your report!

**Comment by XxRexRaptorxX** [comment]
fixed with v.4.2.2
