### ISSUE TITLE
Ships generated in water have air pockets around them

### ISSUE THREAD

**Issue by LiskoSlayer63** [XxRexRaptorxX/Additional-Structures#4]
**I think this image explains it all:**

![kuva](https://user-images.githubusercontent.com/10125529/77524538-2bf45400-6e90-11ea-928f-1844bebb43fe.png)

**Additional Structures version:** 2.3.1
**Forge version:** 14.23.5.2847
**Minecraft version:** 1.12.2

**Comment by XxRexRaptorxX** [comment]
Structure is not from Additional Structures
