### ISSUE TITLE
Broken link to download structures world

### ISSUE THREAD

**Issue by ChefMC** [XxRexRaptorxX/Additional-Structures#5]
Dropbox link [on this page](https://www.curseforge.com/minecraft/mc-mods/additional-structures/pages) is unavailable anymore. Can you reupload please? I can't use your mod on 1.7.10, but I very like this structures and want to import them in our general mod for structures generating. Thanks a lot!

**Comment by XxRexRaptorxX** [comment]
Link is fixed.
Please don't use my structures in other mods
